
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
categories:
  - title: '🚀 Features'
    labels: ['feature', 'enhancement']
  - title: '🧰 Maintenance'
    labels: ['chore', 'refactor']
  - title: '🐛 Fixes'
    labels: ['fix', 'bug']
  - title: '📝 Docs'
    labels: ['docs']
template: |
  ## Changes
  $CHANGES

  ## Contributors
  $CONTRIBUTORS
